riboswitches_app/database/urls.py
from django.conf.urls import url
from . import views

app_name = 'database'

urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^help/about/$', views.help, name='help'),
    url(r'^browser/ligand/$', views.ligand_browser, name='ligand_browser'),
    url(r'^browser/ligand/(?P<ligand_name>[A-Za-z]+)/$', views.ligand_details, name='ligand_details'),
    url(r'^browser/organism/$', views.organism_browser, name='organism_browser'),
    url(r'^browser/organism/(?P<organism_name>([-\w\s.()])+)/$', views.organism_details, name='organism_details'),
    url(r'^browser/class/family$', views.class_family_browser, name="class_family_browser"),
    url(r'^browser/class/family/(?P<family>([-\w\s.()_/])+)/$', views.class_family_details, name='class_family_details'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^searcher/$', views.searcher, name='searcher'),
    url(r'^search/gene/(?P<gene_name>[\w_]+)/$', views.gene_details, name='gene_details'),
    url(r'^search/organism/(?P<organism_name>([-\w\s.()_/])+)/$', views.organism_details, name='organism_details'),
]

riboswitches_app/riboswitches_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('database.urls')),
    url(r'^search/', include('search.urls'))
]

riboswitches_app/search/urls.py
from django.conf.urls import url
from . import views
from database import views as db_views

app_name = 'search'
urlpatterns = [
  
  url(r'^genes/$', views.genes),
  url(r'^organisms/$', views.organisms),
  url(r'^ligands/$', views.ligands),
  url(r'^$', db_views.index, name="index"),
  url(r'^record/(?P<riboswitch_name>([A-Za-z0-9|\W])+)/$', views.record, name="record"),
]

riboswitches_app/database/models.py
from django.db import models

'''
This are Django models which we use to create our database. Each database table is a class.
ForeignKey, OneToOneField and ManyToManyField refer connections in database.
We use default values temporary - they help us to fill database with sample values.
'''

class Record(models.Model):
	family = models.ForeignKey('RiboFamily', null = True)
	gene = models.OneToOneField('Gene', null = True, related_name = 'gene')
	genes_under_operon_regulation = models.ManyToManyField('Gene', related_name = 'operon_gene')
	terminator = models.OneToOneField('Position', null = True, related_name = 'terminator')
	promoter = models.OneToOneField('Position', null = True, related_name = 'promoter')
	shinedalgarno = models.OneToOneField('Position', null = True, related_name = 'shinedalgarno')
	articles = models.ManyToManyField('Article', related_name = 'article')
	sequence = models.TextField('sekwencja')
	
	EFFECT_CHOICES = ( 
		('+', 'ACTIVATION'),
		('.', 'UNKNOWN'),
		('-', 'SILECING'),
	)
	effect = models.CharField(max_length = 1, choices = EFFECT_CHOICES, default = '.')
	MECHANISM_CHOICES = (
		('TRN', 'TRANSCRIPTION'),
		('TRL', 'TRANSLATION'),
		('UN', 'UNKNOWN'),
		('DG', 'DEGRADATION'),
	)
	mechanism = models.CharField(max_length = 3, choices = MECHANISM_CHOICES, default = 'UN')
	mechanism_confirmation = models.ForeignKey('Article', related_name = 'confirmation', null = True)

	def __str__(self):
		return 'RECORD: |{}| |{}| |{}| |{}| |{}| |{}| |{}| {} {} |{}| {}'.format(self.family, self.aptamer_set.all(), self.gene, self.terminator, self.promoter, self.articles.all(), self.genes_under_operon_regulation.all(), self.effect, self.mechanism, self.mechanism_confirmation, self.sequence)

	def name(self):
		return "RS{}".format((str(self.id).zfill(8)))

class Aptamer(models.Model):
	position = models.OneToOneField('Position', null = True, related_name = 'aptamer_position')
	structure = models.OneToOneField('Structure2D', null = True)
	switch = models.ForeignKey('Record')

	def __str__(self):
		return 'Apt: |{}| |{}|'.format(self.position, self.structure)


class Structure2D(models.Model):
	without_ligand = models.TextField('bez_ligandu')
	with_ligand = models.TextField('z_ligandem')
	predicted = models.TextField('przewidziana')

	def __str__(self):
		return 'Struct: {} {} {}'.format(self.without_ligand, self.with_ligand, self.predicted)


class Article(models.Model):
	pmid = models.IntegerField(primary_key = True)

	def __str__(self):
		return 'Art: {}'.format(self.pmid)


class Structure3D(models.Model):
	pdbid = models.CharField(max_length = 10, primary_key = True)
	ribo_class = models.ForeignKey('RiboClass')

	def __str__(self):
		return 'Str3D: {}'.format(self.pdbid)


class RiboFamily(models.Model):
	ribo_class = models.ForeignKey('RiboClass', null = True)
	name = models.CharField('nazwa', max_length = 10, primary_key = True)
	description = models.TextField('opis')
	alignment = models.TextField('dopasowanie')

	def __str__(self):
		return 'RFam: {} {} {} |{}|'.format(self.name, self.description, self.alignment, self.ribo_class)


class RiboClass(models.Model):
	# Accesion number???
	name = models.CharField('nazwa', max_length = 10, primary_key = True)
	description = models.TextField('opis')
	alignment = models.TextField('dopasowanie')
	ligands = models.ManyToManyField('Ligand')

	def __str__(self):
		return 'RCl: {} {} {} |{}|'.format(self.name, self.description, self.alignment, self.ligands.all())


class Gene(models.Model):
	organism = models.ForeignKey('Organism', null = True) 
	name = models.CharField('nazwa', max_length = 20, null = False)
	locus_tag = models.CharField(max_length = 15)
	position = models.OneToOneField('Position', null = True, related_name = 'gene_position')
	def __str__(self):
		return 'Gene: |{}| {} {} |{}|'.format(self.organism, self.name, self.locus_tag, self.position)


class Organism(models.Model):
	scientific_name = models.CharField('nazwa_naukowa', max_length = 250)
	common_name = models.CharField('nazwa_zwyczajowa', max_length = 250)
	accession_number = models.CharField('numer_dostepu', max_length = 30)
	build_id = models.CharField('numer_dostepu', max_length = 30, primary_key = True)
	taxonomy = models.OneToOneField('Taxonomy', null = True)

	def __str__(self):
		return 'Or: {} {} {} {} |{}|'.format(self.scientific_name, self.common_name, self.accession_number, self.build_id, self.taxonomy)


class Taxonomy(models.Model):
	name = models.CharField('nazwa', max_length = 20, null = True)
	taxonomy_id = models.IntegerField('taxid', default = 0, primary_key = True)
	parent = models.ForeignKey('Taxonomy', null = True)

	def __str__(self):
		return 'Tax: {} {} |{}|'.format(self.name, self.taxonomy_id, self.parent)


class LigandClass(models.Model):
	name = models.CharField('nazwa', max_length = 20, primary_key = True)
	description = models.TextField('opis')

	def __str__(self):
		return 'LiC: {} {}'.format(self.name, self.description)


class Ligand(models.Model):
	ligand_class = models.ForeignKey('LigandClass', null = True)
	name = models.CharField('nazwa', max_length = 20, primary_key = True)
	description = models.TextField('opis')
	image_name = models.TextField('nazwa pliku')

	def __str__(self):
		return 'Li: |{}| {} {} {}'.format(self.ligand_class, self.name, self.description, self.image_name)


class Position(models.Model):
	start = models.IntegerField(default = 0)
	end = models.IntegerField(default = 0)
	location = models.TextField('opis')
	score = models.FloatField(default = 0.0)
	STRAND_CHOICES = (
		('+', 'LEADING STRAND'),
		('.', 'UNKNOWN'),
		('-', 'LAGGING STRAND'),
	)
	strand = models.CharField(max_length = 1, choices = STRAND_CHOICES, default = '.')

	def __str__(self):
		return "Start: {}, End: {}, Score: {}, Location: {}, Strand: {}".format(self.start, self.end, self.score, self.location, self.strand)

riboswitches_app/database/views.py
from django.shortcuts import render
from django.http import JsonResponse

from .models import Gene, Organism, Ligand, RiboFamily, Record, RiboClass, Taxonomy, \
                    LigandClass
import json, re

def help(request):

    return render(request, 'database/help.html')

def contact(request):

    context = {
        'api_key': 'AIzaSyAVR8tS7DwduYSSWCkKgAgjKuS1ZGyWaeA',
    }

    return render(request, 'database/contact.html', context)

def index(request):

    context = {'breadcrumbs': []}
    return render(request, 'database/index.html', context)

def searcher(request):

    recordList = []

    for e in Record.objects.all():
        if e.family != None:
            dic = {
                'name': e.name,
                'gene' : None,
                'ligand': None,
                'organism': None,
            }
            dic['ligand'] = e.family.ribo_class.ligands.all()[0].name if e.family.ribo_class.ligands.all() else dic['ligand']
            dic['gene'] = e.gene.name if e.gene.name != None else dic['gene']
            dic['organism'] = e.gene.organism.scientific_name if e.gene.organism.scientific_name != None else dic['organism']
            recordList.append(dic.copy())

    context = {
        'recordList': recordList,
    }

    return render(request, 'database/searcher.html', context)

def class_family_browser(request):

    result = []
    families = []
    class_list = RiboClass.objects.all()

    for i in RiboClass.objects.all():
        dic = {
            'name': None,
            'families': None,
        }
        dic['name'] = i.name
        for j in RiboFamily.objects.all():
            print(j)
            if j.ribo_class.name == i.name:
                families.append(j.name)
            dic['families'] = families
        families = []
        result.append(dic.copy())
    context = {
        'result': result,
    }

    return render(request, 'database/class_family_browser.html', context)

def class_family_details(request, family):

    families_list = []

    for e in Record.objects.all():
        if e.family != None:
            if family == e.family.name:
                organism = e.gene.organism.scientific_name
                families_list.append(organism)

    context = {
        'families_list': set(families_list),
    }

    return render(request, 'database/class_family_details.html', context)

def gene_details(request, gene_name):

    recordList = []
    name = gene_name

    for e in Record.objects.all():
        if gene_name in str(e.gene.name):
            dic = {
                'id': e.id,
                'name': e.name(),
                'gene': None,
            }
            dic['name'] = e.name() if e.name() != None else dic['name']
            dic['gene'] = e.gene.name if e.gene.name != None else dic['gene']
            recordList.append(dic.copy())

    context = {
        'recordList': recordList,
        'name': name,
    }

    return render(request, 'database/ligand_details.html', context)


def ligand_browser(request):

    context = {
        'glycine': 'Glycine',
        'alanine': 'Alanine',
        'sam': 'SAM',
        'FMN': 'FMN',
        'adenine': 'Adnenine',
        'guanine': 'Guanine',
    }

    return render(request, 'database/ligand_browser.html', context)

def ligand_details(request, ligand_name):

    recordList = []
    name = ligand_name

    for e in Record.objects.all():
        if e.family != None:
            print(e.family.ribo_class.ligands.all())
            if ligand_name in str(e.family.ribo_class.ligands.all()):
                dic = {
                    'id': e.id,
                    'name': e.name,
                    'ligand': None,
                }
                dic['name'] = e.name if e.name != None else dic['name']
                dic['ligand'] = e.family.ribo_class.ligands.all()[0].name if e.family.ribo_class.ligands.all() != None else dic['ligand']
                recordList.append(dic.copy())

    context = {
        'recordList': recordList,
        'name': name,
    }


    return render(request, 'database/ligand_details.html', context)

### BEST BROWSER IN THE WHOLE UNIVERSE ###

def create_tax(tax_list, parent_id, data):

    for tax in tax_list:
        tax_name = tax.name
        data.append({
            "id": tax_name, "parent": parent_id, "text": tax_name
        })
        create_tax(
            tax.taxonomy_set.all(), tax_name, data
        )


def organism_browser(request):

    data = []
    counter = 0

    tax_list_tree = []
    current_tax = Taxonomy.objects.get(name = 'Bacteria')
    tax_list_tree.append(current_tax.name)

    data.append({
        "id": current_tax.name, "parent": "#", "text": current_tax.name
    })

    create_tax(current_tax.taxonomy_set.all(), current_tax.name, data)

    d = { 
        'core' : {
            'data' : data,
        },
        'types' : {
            "default" : {
                "icon" : "/static/database/images/folder-24.png"
            },
            "folder-open" : {
                "icon" : "/static/database/images/open-folder-24.png"
            },
        },
        "themes": {
            "dots": True
        },
        "plugins" : [ "types", ] 
    }

    parents = []
    childrens = []

    for i in data:
        parents.append(i['parent'])

    for i in data:
        if i['id'] not in parents:
            childrens.append(i['id'])

    ddumps = json.dumps(d)

    context = {
        'tax_list_tree': tax_list_tree,
        'd': ddumps,
        'childrens': childrens,
    }

    return render(request, 'database/organism_browser.html', context)



##########################################################################################


def organism_details(request, organism_name):

    term = request.get_full_path()
    match = re.findall(r'[/](.*?)[/]',term)[-1].replace('%20', ' ')


    riboswitch_record = []

    for e in Record.objects.all():
        if match == str(e.gene.organism.scientific_name):
            dic = {
                'id': e.id,
                'name': e.name(),
                'scientific_name': None,
            }
            dic['name'] = e.name() if e.name() != None else dic['name']
            dic['scientific_name'] = e.gene.organism.scientific_name if e.gene.organism.scientific_name != None else dic['scientific_name']
            riboswitch_record.append(dic.copy())

    context = {
        'riboswitch_record': riboswitch_record,
    }

    return render(request, 'database/organism_details.html', context)

riboswitches_app/database/templates/database/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Meta tags -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>RISE | {% block _title %} {% endblock %}</title>
    
    <!-- Custom css -->
    <link href="{% static "database/css/custom.css" %}" rel="stylesheet"> 
    <!-- Bootstrap -->
    <link href="{% static "database/plugins/bootstrap/styles/bootstrap.css" %}" rel="stylesheet">
    <!-- font-awesome icons -->
    <link href="{% static "database/css/font-awesome.css" %}" rel="stylesheet" type="text/css" >
    <link href="{% static "database/css/fontawesome-webfont.eot" %}" >
    <link href="{% static "database/css/fontawesome-webfont.woff" %}" >
    <!-- Roboto google font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    {% block css_plugins %}
    {% endblock %}
  
  </head>
  <body>
  
    <!-- Document wrapper -->
    <div id="wrapper">

      <!-- Navbar -->
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header" id="nav-cont">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span> 
            </button>
            <a class="navbar-brand" href="{% url 'database:index' %}" id="title">RISE</a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right" id="nav-ul">
              <li><a href="{% url 'database:searcher' %}">Search</a></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Browse
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'database:ligand_browser' %}">By ligand</a></li>
                  <li><a href="{% url 'database:organism_browser' %}">By organism</a></li>
                  <li><a href="{% url 'database:class_family_browser' %}">By class/family</a></li>
                </ul>
              </li>
              <li><a href="{% url 'database:help' %}" id="help">Help</a></li>
              <li><a href="{% url 'database:contact' %}" id="contact">Contact</a></li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End navbar -->

      <!-- Main contet from other templates -->
      <main class="fade-out">
        {% block content %}
           
        {% endblock %}
      <main>
      <!-- End content -->

      <!-- Footer -->
      <footer id="footer">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 text-center">
              <p class="text-muted">2017 &copy; Combio</p>
            </div>
          </div>
        </div>
      </footer> 
      <!-- End footer -->

    </div>
    <!-- End wrapper -->


    <!-- jQuery required before Bootstrap.js -->
    <script src="{% static "database/js/jquery-3.2.1.min.js" %}"></script>

    <!-- Custom js script -->
    <script src="{% static "database/js/custom.js" %}"></script>

    <!-- Basic scripts -->
    <script src="{% static "database/plugins/bootstrap/scripts/bootstrap.min.js" %}"></script>

    <!-- Specific plugins for particular site -->
    {% block js_plugins %}
    {% endblock %}
    
  </body>
</html>

riboswitches_app/database/templates/database/class_family_browser.html
{% extends 'database/base.html' %}
{% load static %}

{% block _title %}
  Details
{% endblock %}

{% block css_plugins %}
<!-- Js tree styles -->
<link href="{% static "database/plugins/jstree/themes/default/style_jstree.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">

  <!-- Nav helper -->
  <div class="bs-example">
      <ul class="breadcrumb">
        <span class="glyphicon glyphicon-home"></span>
          <li><a href="{% url 'database:index' %}" id="test">Home</a></li>
          <li class="active">Browse</li>
          <li class="active">By class/family</li>
          <span data-toggle="popover" class="glyphicon glyphicon-question-sign glyphicon-help pull-right" title="Class/family browser" data-content="This part of browsing lets you to find riboswitches for specifi classes and families. The number next to a class name represents the number of families for this class." data-trigger="hover" data-placement="left"></span>
      </ul>
  </div>

  <div class="panel panel-default panel-no-margin">
      <div class="panel-heading">
          <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion" href="#filterPanel">Browse classes and families</a>
              <span class="pull-right panel-collapse-clickable" data-toggle="collapse" data-parent="#accordion" href="#filterPanel">
                  <i class="glyphicon glyphicon-chevron-down"></i>
              </span>
          </h4>
      </div>
      <div id="filterPanel" class="panel-collapse collapse in">
          <div class="panel-body">
              <!-- Start of jstree list -->
                <div id="jstree-class">
                  <ul>
                    <!-- loop through all classes -->
                    {% for class in result %}
                      <li>{{ class.name }}
                        <span class="badge progress-bar-success">
                          {{ class.families|length }}
                        </span>
                        <ul>
                        <!-- loop through families for a class -->
                          {% for family in class.families %}
                            <li>
                              <a href="{% url 'database:class_family_details' family %}">
                                {{ family }}
                              </a>
                            </li>
                          {% endfor %}
                        </ul>
                      </li>
                    {% endfor %}
                  </ul>
                </div>  
                <!-- End of jstree list -->  
          </div>
      </div>
  </div>

</div>
{% endblock %}

{% block js_plugins %}
<!-- jstree script -->
<script src="{% static "database/plugins/jstree/scripts/jstree.min.js" %}"></script>
<script src="{% static "database/plugins/jstree/scripts/jstree_custom.js" %}"></script>
<script>$(".glyphicon-question-sign").popover();</script>
{% endblock %}

riboswitches_app/database/templates/database/class_family_details.html
{% extends 'database/base.html' %}
{% load static %}

{% block _title %}
  Details
{% endblock %}

{% block css_plugins %}
<!-- dataTables for Bootstrap -->
<link rel="stylesheet" type="text/css" href="{% static "database/plugins/datatables/styles/datatables.bootstrap.min.css" %}">
{% endblock %}

{% block content %}

<div class="container">

  <!-- Nav helper -->
  <div class="bs-example">
    <ul class="breadcrumb">
      <span class="glyphicon glyphicon-home"></span>
      <li><a href="{% url 'database:index' %}">Home</a></li>
      <li class="active">Browse</li>
      <li class="active">By class/family</li>
      <span data-toggle="popover" class="glyphicon glyphicon-question-sign glyphicon-help pull-right" title="Class/family browsing results" data-content="On this page you see a table of riboswitches, which are results of your browsing." data-trigger="hover" data-placement="left"></span>
    </ul>
  </div>

  <div class="dataTables wrapper form-inline dt-bootstrap no-footer">
    <div class="col-xs-12" id="table_wrapper">
      <table id="family-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
          <tr>
            <th>Organisms</th>
          </tr>
        </thead>
        <tbody>
          {% for detail in families_list %}
            <tr role="row">
              <td><a href="{% url 'database:organism_details' detail %}">{{ detail }}</a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</div>

{% endblock %}

{% block js_plugins %}
<script src="{% static "database/plugins/datatables/scripts/datatables.min.js" %}"></script>
<script src="{% static "database/plugins/datatables/scripts/datatables_custom.js" %}"></script>
<script>$(".glyphicon-question-sign").popover();</script>
{% endblock %}

riboswitches_app/database/templates/database/ligand_details.html
{% extends 'database/base.html' %}
{% load static %}

{% block _title %}
  Details
{% endblock %}

{% block css_plugins %}
<!-- dataTables for Bootstrap -->
<link rel="stylesheet" type="text/css" href="{% static "database/plugins/datatables/styles/datatables.bootstrap.min.css" %}">
{% endblock %}

{% block content %}

	<div class="container">
		  <!-- Nav helper -->
		  <div class="bs-example">
		      <ul class="breadcrumb">
		      	<span class="glyphicon glyphicon-home"></span>
		          <li><a href="{% url 'database:index' %}">Home</a></li>
		          <li class="active">Browse</li>
		          <li><a href="{% url 'database:ligand_browser' %}">By ligand</a></li>
		          <li class="active">{{ name }}</li>
		          <span data-toggle="popover" class="glyphicon glyphicon-question-sign glyphicon-help pull-right" title="Browsing result page" data-content="On this page, you see all the riboswitches which are results of browsing." data-trigger="hover" data-placement="left"></span>
		      </ul>
		  </div>
			
		
			<div class="dataTables wrapper form-inline dt-bootstrap no-footer">
				<div class="col-xs-12" id="table_wrapper" >
					<table id="ligand-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>Riboswitch</th>
							</tr>
						</thead>
							<tbody>
							{% for rr in recordList %}
								<tr role="row">
									<td><a href="{% url 'search:record' rr.name %}">{{ rr.name }}</a></td>
								</tr>
							{% endfor %}
							</tbody>
					</table>
				</div>
	
			</div>
		</div>

{% endblock %}

{% block js_plugins %}
<script src="{% static "database/plugins/datatables/scripts/datatables.min.js" %}"></script>
<script src="{% static "database/plugins/datatables/scripts/datatables_custom.js" %}"></script>
<script>$(".glyphicon-question-sign").popover();</script>
{% endblock %}

riboswitches_app/database/templates/database/organism_details.html
{% extends 'database/base.html' %}
{% load static %}

{% block _title %}
  Details
{% endblock %}

{% block css_plugins %}
<!-- dataTables for Bootstrap -->
<link rel="stylesheet" type="text/css" href="{% static "database/plugins/datatables/styles/datatables.bootstrap.min.css" %}">
{% endblock %}

{% block content %}

	<div class="container">
		  <!-- Nav helper -->
		  <div class="bs-example">
		      <ul class="breadcrumb">
		      	<span class="glyphicon glyphicon-home"></span>
		          <li><a href="{% url 'database:index' %}">Home</a></li>
		          <li class="active">Browse</li>
		          <li><a href="{% url 'database:organism_browser' %}">By organism</a></li>
		          <li class="active">{{ name }}</li>
		          <span data-toggle="popover" class="glyphicon glyphicon-question-sign glyphicon-help pull-right" title="Browsing result page" data-content="On this page, you see all the riboswitches which are results of browsing." data-trigger="hover" data-placement="left"></span>
		      </ul>
		  </div>
			
			<div class="dataTables wrapper form-inline dt-bootstrap no-footer">
				<div class="col-xs-12" id="table_wrapper" >
					<table id="ligand-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th>Riboswitch</th>
							</tr>
						</thead>
							<tbody>
							{% for i in riboswitch_record %}
								<tr role="row">
									<td><a href="{% url 'search:record' i.name %}">{{ i.name }}</a></td>
								</tr>
							{% endfor %}
							</tbody>
					</table>
				</div>
	
			</div>
		</div>

{% endblock %}

{% block js_plugins %}
<script src="{% static "database/plugins/datatables/scripts/datatables.min.js" %}"></script>
<script src="{% static "database/plugins/datatables/scripts/datatables_custom.js" %}"></script>
<script>$(".glyphicon-question-sign").popover();</script>
{% endblock %}

riboswitches_app/database/templates/database/searcher.html
{% extends 'database/base.html' %}
{% load static %}

{% block _title %}Search{% endblock %}

{% block css_plugins %}
<!-- dataTables for Bootstrap -->
<link rel="stylesheet" type="text/css" href="{% static "database/plugins/datatables/styles/datatables.bootstrap.min.css" %}">
{% endblock %}

{% block content %}
<div class="container">
  <!-- Nav helper -->
  <div class="bs-example">
    <ul class="breadcrumb">
      <li>
        <span class="glyphicon glyphicon-home"></span>
        <a href="{% url 'database:index' %}">
          Home
        </a>
      </li>
      <li class="active">
        Search
      </li>
      <span data-toggle="popover" class="glyphicon glyphicon-question-sign glyphicon-help pull-right" title="Searcher" data-content="This is a searcher. On this page, there are displaying all the riboswitches from the database. You can eaisly filter the results using the inputs on the bottom of the page. In order to see the record, you should click on a riboswitch name." data-trigger="hover" data-placement="left"></span>
    </ul>
  </div>

  <!-- <div id="table_wrapper" class="dataTables wrapper form-inline dt-bootstrap"> -->
    <div class="col-xs-12" id="table_wrapper">
      <table id="search-table" class="display table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
          <tr>
            <th>Riboswitch</th>
            <th>Gene</th>
            <th>Ligand</th>
            <th>Organism</th>
          </tr>
        </thead>
        <tfoot>
            <tr>
                <th>Name</th>
                <th>Gene</th>
                <th>Ligand</th>
                <th>Organism</th>
            </tr>
        </tfoot>
        <tbody>
        {% for rr in recordList %}
          <tr role="row">
            <td><a href="{% url 'search:record' rr.name %}">{{ rr.name }}</a></td>
            <td>{{ rr.gene }}</td>
            <td>{{ rr.ligand }}</td>
            <td>{{ rr.organism }}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

  <!-- </div> -->


</div>

{% endblock %}

{% block js_plugins %}
<script src="{% static "database/plugins/datatables/scripts/datatables.min.js" %}"></script>
<script src="{% static "database/js/datatables_search.js" %}"></script>
<script>
$(".glyphicon-question-sign").popover();
</script>
{% endblock %}